version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    hostname: mongodb
    ports:
      - "27017:27017"
    networks:
      epc-network:
        ipv4_address: 192.168.24.10
  mongo-gui:
    build: webui
    image: aahad91/epc-webui
    container_name: "webui"
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      DB_URI: mongodb://mongodb:27017/open5gs
    entrypoint:
      - "/bin/bash"
      - "./start.sh"
    tty: true
    networks:
      epc-network:
        ipv4_address: 192.168.24.30
  imsi-loader:
    build: mongodb
    image: aahad91/mongodbloader
    container_name: "imsi-loader"
    depends_on:
      - mongo-gui
    entrypoint:
      - "/bin/sh"
      - "./start.sh"
    networks:
      epc-network:
        ipv4_address: 192.168.24.50
  epc:
    build: base1
    image: aahad91/epc-base
    depends_on:
      - mongodb
      - mongo-gui
    hostname: epc
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      DB_URI: mongodb://mongodb:27017/open5gs
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.forwarding=1
    entrypoint:
      - "/bin/bash"
      - "./start.sh"
    tty: true
    networks:
      epc-network:
        ipv4_address: 192.168.24.20
      test-network:
        ipv4_address: 192.168.30.20
  enb:
    build: srsLTE
    image: aahad91/epc-enb
    container_name: enb
    depends_on:
      - epc
    ipc: shareable
    cap_add:
      - SYS_NICE
    entrypoint:
      - "/bin/bash"
      - "./start_enb.sh"
    tty: true
    networks:
      epc-network:
        ipv4_address: 192.168.24.40
  ue:
    build: srsLTE
    image: aahad91/epc-ue
    container_name: ue
    depends_on:
      - enb
    ipc: "container:enb"
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    devices:
      - /dev/net/tun
    #network_mode: "none"
    tty: true
    entrypoint:
      - "/bin/bash"
      - "./start_ue.sh"
    networks:
      dummy-network:
        ipv4_address: 192.168.50.10
  test-server:
    build: iperfSRV
    image: aahad91/iperfsrv
    container_name: test-server
    depends_on:
      - ue
    tty: true
    cap_add:
      - NET_ADMIN
    entrypoint:
      - "/bin/bash"
      - "./start.sh"
    networks:
      test-network:
        ipv4_address: 192.168.30.10
networks:
  epc-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.24.0/24
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.30.0/24
  dummy-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24
