version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    hostname: mongodb
    ports:
      - "27017:27017"
  mongo-gui:
    build: webui
    image: aahad91/epc-webui
    container_name: "webui"
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - DB_URI = mongodb://mongodb/open5gs
    entrypoint:
      - "/bin/bash"
  epc:
    build: base
    image: aahad91/epc-base
    depends_on:
      - mongodb
    hostname: epc
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - DB_URI = mongodb://mongodb/open5gs
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
#    command: /bin/bash -c" chmod 666 /dev/net/tun \ /setup.sh \ /install.sh || exit 0"
    entrypoint:
      - "/bin/bash"
      - "/install.sh"
