descriptor_extension: yml
version: '0.5'
files:
  - path: ns-telco-epc.yml
    type: application/vnd.5gtango.nsd
    tags:
    - eu.5gtango
  - path: vnf-telco-mongodb.yml
    type: application/vnd.5gtango.vnfd
    tags:
    - eu.5gtango
  - path: vnf-telco-imsiloader.yml
    type: application/vnd.5gtango.vnfd
    tags:
    - eu.5gtango
  - path: vnf-telco-enb.yml
    type: application/vnd.5gtango.vnfd
    tags:
    - eu.5gtango
  - path: vnf-telco-epc.yml
    type: application/vnd.5gtango.vnfd
    tags:
    - eu.5gtango
  - path: vnf-telco-testserver.yml
    type: application/vnd.5gtango.vnfd
    tags:
    - eu.5gtango
package:
  name: ns-telco-epc
  version: '0.1'
  maintainer: Abdul Ahad
  vendor: de.upb
  description: test for benchmarking (telco)
